// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kvharpkrttiuvwdrptii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2aGFycGtydHRpdXZ3ZHJwdGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NTA4MzIsImV4cCI6MjA4OTUyNjgzMn0.6fvTAFITyvH_wHrYnRMCVNg1djuhqmPgAV11H9W0Z9E";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);